# Generated by Django 3.0.2 on 2020-01-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('age',models.SmallIntegerField()),
                ('wage', models.SmallIntegerField()),
                ('work', models.CharField(max_length=100)),
                ('aim', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
