# Generated by Django 3.0.2 on 2020-01-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claim',
            name='wage',
            field=models.SmallIntegerField(default=0),
        ),
    ]
