# Generated by Django 3.0.dev20190703113551 on 2020-01-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200105_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='wage',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
