# Generated by Django 3.0.dev20190703113551 on 2020-01-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200107_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='age',
            field=models.SmallIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='wage',
            field=models.SmallIntegerField(default=False),
        ),
    ]
