# Generated by Django 3.0.dev20190703113551 on 2020-01-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20200107_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='claim',
            name='wage',
            field=models.CharField(max_length=50),
        ),
    ]
