# Generated by Django 3.0.dev20190703113551 on 2020-01-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20200108_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='age',
            field=models.CharField(max_length=2, verbose_name='Укажите Ваш возраст'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='aim',
            field=models.CharField(max_length=100, verbose_name='Введите цель получения кретида/займа'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='claim',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Введите Ваше имя'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(blank=True, choices=[('о', 'Одобрено'), ('н', 'Не одобрено'), ('в', 'В разработке')], default='о', help_text='Состояние заявки', max_length=1),
        ),
        migrations.AlterField(
            model_name='claim',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Введите Вашу фамилию'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='wage',
            field=models.CharField(max_length=50, verbose_name='Укажите размер Вашей з/п'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='work',
            field=models.CharField(max_length=100, verbose_name='Место Вашей работы'),
        ),
    ]
