# Generated by Django 3.0.dev20190703113551 on 2020-02-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20200131_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('0', 'В разработке'), ('1', 'Одобрено'), ('2', 'Не одобрено')], default=0, max_length=2),
        ),
    ]
